CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectid INTEGER REFERENCES project(id)
);

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES('Make a web app', 1, 'Using Javascript', '2020-02-07');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES('Make an App', 1, 'Using Dart', '2020-02-10');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES('Make a Desktop App', 1, 'Using Python', '2020-02-10');

INSERT INTO tasks(name, done, projectid)
    VALUES('download Vuejs', false, 1);

INSERT INTO tasks(name, done, projectid)
    VALUES('Create UI WEB', false, 1);

INSERT INTO tasks(name, done, projectid)
    VALUES('download Flutter', false, 2);

INSERT INTO tasks(name, done, projectid)
    VALUES('Design UI', false, 2);